services:
  - type: web
    name: piper-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node dist/index.js
    envVars:
      - key: NODE_OPTIONS
        value: --max-old-space-size=512
